name: Trivy Vulnerabilities Scan

on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  trivy-vuln-scan:
    env:
      TF_VERSION: 1.4.0
    name: Running Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   sparse-checkout: ./examples/

      - name: Cache Terraform
        id: cache-terraform
        uses: actions/cache@v4
        with:
          path: ~/bin
          key: terraform-${{ env.TF_VERSION }}

      - name: Download terraform
        if: steps.cache-terraform.outputs.cache-hit != 'true'
        run: |
          mkdir -p "${HOME}/bin"
          curl -sSL -o terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
          unzip terraform.zip
          mv -v terraform "${HOME}/bin/terraform"
          ~/bin/terraform version

      - name: Run terraform init
        run: |
          ~/bin/terraform -chdir=aws init
          ~/bin/terraform -chdir=azure init
          ~/bin/terraform -chdir=gcp init
          ~/bin/terraform -chdir=openstack init
          ~/bin/terraform -chdir=ovh init

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          scanners: "misconfig"
          severity: "CRITICAL,HIGH"
          #   format: "sarif"
          #   output: "trivy-results.sarif"
          output: trivy.txt

      #   - name: Upload Trivy scan results to GitHub Security tab
      #     uses: github/codeql-action/upload-sarif@v3
      #     with:
      #       sarif_file: "trivy-results.sarif"
      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
          {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
          fi
