name: Trivy Vulnerabilities Scan

on:
  pull_request:

jobs:
  trivy-vuln-scan:
    name: Running Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.59.0

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          scanners: "misconfig"
          severity: "CRITICAL,HIGH,MEDIUM"
          #   format: "sarif"
          #   output: "trivy-results.sarif"
          output: trivy.txt
          skip-setup-trivy: true

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: "trivy-results.sarif"

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
          {
            echo "### Security Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```terraform'
            cat trivy.txt
            echo '```'
            echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
            fi
